repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-json
    - id: check-merge-conflict
    - id: check-yaml
    - id: trailing-whitespace
    - id: end-of-file-fixer
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.96.2
  hooks:
    - id: terraform_validate
      args:
        - '--envs=AWS_DEFAULT_REGION=us-east-1'
    - id: terraform_fmt
    - id: terraform_docs
- repo: https://github.com/psf/black
  rev: 24.10.0 # Replace by any tag/version: https://github.com/psf/black/tags
  hooks:
    - id: black
      language_version: python3 # Should be a command that runs python3.6+
